[package]
name = "adapter-common"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
core-model = { path = "../../core-model" }
rayon.workspace = true
serde_json.workspace = true
tracing.workspace = true
