[package]
name = "embeddings"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
ort = { version = "2.0.0-rc.9", features = ["ndarray", "load-dynamic"] }
ndarray = "0.17"
tokenizers = { version = "0.21", default-features = false, features = ["onig"] }
thiserror = "2"
